export const SERVICES = [
  // Men's Wear
  { name: "Wash - Apron (Doctor white)", price: 49 },
  { name: "Dry Clean - Apron (Doctor white)", price: 89 },
  { name: "Ironing - Apron", price: 15 },
  { name: "Steam Ironing - Apron", price: 27 },
  { name: "Dry Clean - Coat/Blazer", price: 249 },
  { name: "Steam Ironing - Coat/Blazer", price: 99 },
  { name: "Dry Clean - Mens Suit 2pcs", price: 378 },
  { name: "Dry Clean - Mens Suit 3pcs", price: 479 },
  { name: "Steam Ironing - Mens Suit 2pcs", price: 180 },
  { name: "Steam Ironing - Mens Suit 3pcs", price: 240 },
  { name: "Dry Clean - Sherwani", price: 475 },
  { name: "Steam Ironing - Sherwani", price: 99 },
  { name: "Dry Clean - Sherwani (2pc)", price: 469 },
  { name: "Dry Clean - Sherwani (G pc)", price: 599 },
  { name: "Steam Ironing - Sherwani (2pc)", price: 149 },
  { name: "Steam Ironing - Sherwani (G pc)", price: 199 },
  { name: "Wash - Jacket Full", price: 199 },
  { name: "Dry Clean - Jacket Full", price: 269 },
  { name: "Steam Ironing - Jacket Full", price: 99 },
  { name: "Wash - Jacket Half", price: 149 },
  { name: "Dry Clean - Jacket Half", price: 229 },
  { name: "Steam Ironing - Jacket Half", price: 75 },
  { name: "Dry Clean - Leather Jacket", price: 465 },
  { name: "Steam Ironing - Leather Jacket", price: 195 },
  { name: "Wash - Hoodies", price: 199 },
  { name: "Dry Clean - Hoodies", price: 269 },
  { name: "Steam Ironing - Hoodies", price: 75 },
  { name: "Wash - Swetor Full", price: 149 },
  { name: "Dry Clean - Swetor Full", price: 139 },
  { name: "Steam Ironing - Swetor Full", price: 75 },
  { name: "Wash - Swetor Half", price: 90 },
  { name: "Dry Clean - Swetor Half", price: 189 },
  { name: "Steam Ironing - Swetor Half", price: 75 },
  { name: "Wash - Kurta (Single pc.)", price: 89 },
  { name: "Dry Clean - Kurta (Single pc.)", price: 110 },
  { name: "Ironing - Kurta", price: 20 },
  { name: "Steam Ironing - Kurta", price: 40 },
  { name: "Wash - Pajama (Single pc.)", price: 89 },
  { name: "Dry Clean - Pajama (Single pc.)", price: 99 },
  { name: "Ironing - Pajama", price: 15 },
  { name: "Steam Ironing - Pajama", price: 30 },
  { name: "Wash - Kurta & Pajama (1 Pair)", price: 178 },
  { name: "Dry Clean - Kurta & Pajama (1 Pair)", price: 209 },
  { name: "Ironing - Kurta & Pajama", price: 40 },
  { name: "Steam Ironing - Kurta & Pajama", price: 52 },
  { name: "Wash - Sadrin", price: 149 },
  { name: "Dry Clean - Sadrin", price: 229 },
  { name: "Steam Ironing - Sadrin", price: 75 },
  { name: "Wash - Denim (Jeans)", price: 89 },
  { name: "Dry Clean - Denim (Jeans)", price: 149 },
  { name: "Ironing - Denim", price: 8 },
  { name: "Steam Ironing - Denim", price: 18 },
  { name: "Wash - T-Shirt", price: 49 },
  { name: "Dry Clean - T-Shirt", price: 79 },
  { name: "Ironing - T-Shirt", price: 8 },
  { name: "Steam Ironing - T-Shirt", price: 18 },
  { name: "Wash - Trouser (Pant)", price: 49 },
  { name: "Dry Clean - Trouser (Pant)", price: 109 },
  { name: "Ironing - Trouser", price: 8 },
  { name: "Steam Ironing - Trouser", price: 18 },
  { name: "Wash - Shirt", price: 49 },
  { name: "Dry Clean - Shirt", price: 109 },
  { name: "Ironing - Shirt", price: 8 },
  { name: "Steam Ironing - Shirt", price: 18 },
  { name: "Wash - Charak (Stand) / per cloth", price: 55 },
  { name: "Ironing - Charak", price: 20 },
  { name: "Steam Ironing - Charak", price: 49 },

  // Women's Wear
  { name: "Dry Clean - Baby dress", price: 299 },
  { name: "Steam Ironing - Baby dress", price: 60 },
  { name: "Dry Clean - Baby Jacket", price: 199 },
  { name: "Steam Ironing - Baby Jacket", price: 75 },
  { name: "Wash - Frock", price: 149 },
  { name: "Dry Clean - Frock", price: 199 },
  { name: "Steam Ironing - Frock", price: 45 },
  { name: "Wash - Gown", price: 199 },
  { name: "Dry Clean - Gown", price: 299 },
  { name: "Ironing - Gown", price: 75 },
  { name: "Steam Ironing - Gown", price: 149 },
  { name: "Dry Clean - Designer Gown (Long/Heavy)", price: 349 },
  { name: "Ironing - Designer Gown", price: 75 },
  { name: "Steam Ironing - Designer Gown", price: 199 },
  { name: "Wash - Kurti Or Salwar (Single pc.)", price: 89 },
  { name: "Dry Clean - Kurti Or Salwar (Single pc.)", price: 98 },
  { name: "Ironing - Kurti/Salwar", price: 8 },
  { name: "Steam Ironing - Kurti/Salwar", price: 19 },
  { name: "Wash - Dupatta", price: 49 },
  { name: "Dry Clean - Dupatta", price: 65 },
  { name: "Ironing - Dupatta", price: 15 },
  { name: "Steam Ironing - Dupatta", price: 25 },
  { name: "Wash - Kurti + Salwar + Dupatta (3pc)", price: 109 },
  { name: "Dry Clean - Kurti + Salwar + Dupatta (3pc)", price: 249 },
  { name: "Ironing - Kurti + Salwar + Dupatta", price: 55 },
  { name: "Steam Ironing - Kurti + Salwar + Dupatta", price: 75 },
  { name: "Wash - Suit Designer (2pc)", price: 199 },
  { name: "Dry Clean - Suit Designer (2pc)", price: 299 },
  { name: "Ironing - Suit Designer (2pc)", price: 45 },
  { name: "Steam Ironing - Suit Designer (2pc)", price: 75 },
  { name: "Wash - Suit Designer (3pc)", price: 249 },
  { name: "Dry Clean - Suit Designer (3pc)", price: 494 },
  { name: "Ironing - Suit Designer (3pc)", price: 55 },
  { name: "Steam Ironing - Suit Designer (3pc)", price: 75 },
  { name: "Wash - Saree Simple", price: 149 },
  { name: "Dry Clean - Saree Simple", price: 229 },
  { name: "Ironing - Saree Simple", price: 28 },
  { name: "Steam Ironing - Saree Simple", price: 55 },
  { name: "Wash - Saree+Blouse (Simple)", price: 199 },
  { name: "Dry Clean - Saree+Blouse (Simple)", price: 289 },
  { name: "Ironing - Saree+Blouse", price: 46 },
  { name: "Steam Ironing - Saree+Blouse", price: 70 },
  { name: "Dry Clean - Saree Designer", price: 375 },
  { name: "Ironing - Saree Designer", price: 75 },
  { name: "Steam Ironing - Saree Designer", price: 100 },
  { name: "Dry Clean - Silk Saree", price: 375 },
  { name: "Ironing - Silk Saree", price: 75 },
  { name: "Steam Ironing - Silk Saree", price: 100 },
  { name: "Dry Clean - Saree (Grafyvaram)", price: 375 },
  { name: "Ironing - Saree (Grafyvaram)", price: 75 },
  { name: "Steam Ironing - Saree (Grafyvaram)", price: 100 },
  { name: "Dry Clean - Saree (Banarasi)", price: 375 },
  { name: "Ironing - Saree (Banarasi)", price: 75 },
  { name: "Steam Ironing - Saree (Banarasi)", price: 100 },
  { name: "Wash - Lehenga Simple", price: 299 },
  { name: "Dry Clean - Lehenga Simple", price: 399 },
  { name: "Steam Ironing - Lehenga Simple", price: 195 },
  { name: "Wash - Lehenga Designer/Heavy", price: 499 },
  { name: "Dry Clean - Lehenga Designer/Heavy", price: 799 },
  { name: "Steam Ironing - Lehenga Designer/Heavy", price: 299 },
  { name: "Wash - Shawl/Shawl", price: 49 },
  { name: "Dry Clean - Shawl (Basic)", price: 149 },
  { name: "Dry Clean - Shawl (Premium)", price: 450 },
  { name: "Ironing - Shawl", price: 15 },
  { name: "Steam Ironing - Shawl", price: 27 },
  { name: "Wash - Saree Charak (Starch)", price: 55 },
  { name: "Dry Clean - Saree Charak", price: 69 },
  { name: "Ironing - Saree Charak", price: 28 },
  { name: "Steam Ironing - Saree Charak", price: 55 },

  // Household Non Wearable
  { name: "Dry Clean - Single Bed Blanket 1 Ply", price: 249 },
  { name: "Dry Clean - Single Bed Blanket 2 Ply", price: 249 },
  { name: " Single Bed Blanket 1 Ply", price: 320 },
  { name: " Single Bed Blanket 2 Ply", price: 410 },
  { name: "Dry Clean - Double Bed Blanket 1 Ply", price: 399 },
  { name: "Dry Clean - Double Bed Blanket 2 Ply", price: 499 },
  { name: " Double Bed Blanket 1 Ply", price: 430 },
  { name: " Double Bed Blanket 2 Ply", price: 530 },
  { name: "Dry Clean - Comforter Single", price: 299 },
  { name: "Dry Clean - Comforter Double", price: 399 },
  { name: " Comforter Single", price: 430 },
  { name: " Comforter Double", price: 530 },
  { name: "Dry Clean - Raza/Quilt Single", price: 399 },
  { name: "Dry Clean - Raza/Quilt Double", price: 499 },
  { name: " Raza/Quilt Single", price: 430 },
  { name: " Raza/Quilt Double", price: 530 },
  { name: "Wash - Bed Sheet Single", price: 79 },
  { name: "Wash - Bed Sheet Double", price: 99 },
  { name: "Dry Clean - Bed Sheet Single", price: 159 },
  { name: "Dry Clean - Bed Sheet Double", price: 199 },
  { name: "Ironing - Bed Sheet Single", price: 35 },
  { name: "Ironing - Bed Sheet Double", price: 49 },
  { name: "Steam Ironing - Bed Sheet Single", price: 55 },
  { name: "Steam Ironing - Bed Sheet Double", price: 75 },
  { name: "Wash - Pillow Cover", price: 29 },
  { name: "Dry Clean - Pillow Cover", price: 49 },
  { name: "Ironing - Pillow Cover", price: 8 },
  { name: "Steam Ironing - Pillow Cover", price: 20 },
  { name: "Dry Clean - Carpet (0-25 sq.ft.) per sq.ft.", price: 15 },
  { name: "Dry Clean - Carpet (25-50 sq.ft.) per sq.ft.", price: 13 },
  { name: "Dry Clean - Carpet (>50 sq.ft.) per sq.ft.", price: 11 },
  { name: "Dry Clean - Duvet", price: 90 },
  { name: "Dry Clean - Curtains Door/Window (Without Lining)", price: 170 },
  { name: "Ironing - Curtains", price: 45 },
  { name: "Steam Ironing - Curtains", price: 75 },
  { name: "Dry Clean - Curtains Door/Window (With Lining)", price: 270 },
  { name: "Wash - Single Curtain (Size 4x8)", price: 119 },
  { name: "Dry Clean - Single Curtain (Size 4x8)", price: 199 },
  { name: "Wash - Single Curtain (Size 6x3)", price: 89 },
  { name: "Dry Clean - Single Curtain (Size 6x3)", price: 299 },
  { name: "Dry Clean - Curtain (Panel)", price: 150 },
  { name: "Steam Ironing - Curtain (Panel)", price: 89 },
  { name: "Wash - Raza/Quilt Cover Single", price: 109 },
  { name: "Wash - Raza/Quilt Cover Double", price: 149 },
  { name: "Dry Clean - Raza/Quilt Cover Single", price: 159 },
  { name: "Dry Clean - Raza/Quilt Cover Double", price: 199 },
  { name: "Ironing - Raza/Quilt Cover Single", price: 29 },
  { name: "Ironing - Raza/Quilt Cover Double", price: 49 },
  { name: "Steam Ironing - Raza/Quilt Cover", price: 55 },

  // Shoes
  { name: "Dry Clean - Sports Shoes", price: 350 },
  { name: "Dry Clean - Canvas/Sneakers (Non Leather)", price: 350 },
  { name: "Dry Clean - Leather Shoes", price: 450 },
  { name: "Dry Clean - Suede Leather Shoes", price: 530 },
  { name: "Dry Clean - Boots", price: 590 },

  // Bags
  { name: "Dry Clean - Handbag", price: 399 },
  { name: "Dry Clean - Canvas/Jute/Cloth Bag", price: 299 },
  { name: "Dry Clean - Handbag Leather", price: 699 },
  { name: "Dry Clean - Suit Case", price: 225 },
  { name: "Dry Clean - Wallet", price: 249 },
];